### ISSUE TITLE
Building menu dropdown not automatically activated

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#120]
In general the building dropdown menu isn't working. We usually have to save the record and then edit it to enable the building dropdown menu and select the building. For new transcription we can do this for the first member of the family and then it will save but when going back in and adding addresses to each census record for the town of caroline we then have to save and edit each record individually to attach the building record.

**Comment by PatientRowan** [comment]
I had a problem with the building drop down menu first thing this morning.  It happens when you save “on the same street,” not (in my experience, which is limited) when you save in this dwelling or on this page.  Here’s what it looked like this morning before I saved the record and then edited it add the building:
![8C52B8EE-F7E3-43B1-8962-28C3E0B80F3E](https://user-images.githubusercontent.com/114665933/199050108-52f5c740-a9e9-4d49-af39-804dfe322ad1.png)
