### ISSUE TITLE
Merge in Same Census Year

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#213]
I am delighted that the computer allowed me to make this merge, even though both instances were in the same census year:
![IMG_0384](https://user-images.githubusercontent.com/114665933/234029958-8b5748ea-076d-4e62-bb0d-49fe95013791.jpeg)

**Comment by PatientRowan** [comment]
Did you mean to make this change?  It seemed like a bit of a safety device, although it also meant that I had to write a couple of elaborate work-around documents:

https://docs.google.com/document/d/1Z9a62r2nGDUX5ZYiQWjXpJP7nRgsQiIYo6XopplOJh0/edit#heading=h.lll6mvz3sh9f

https://docs.google.com/document/d/17oaoUGk3tR7pRW3SgMsGbRhPew4G9XeKm77atbQ4f_Y/edit

**Comment by dfurber** [comment]
If I understand what you're asking about, it's definitely intentional. He was counted twice but is the same person. It happens, albeit infrequently.

When I started person records, I had it so that you couldn't do this. It worked well for months, until we encountered a guy in 1920 who was counted at his house, and at his parent's house later on.

**Comment by PatientRowan** [comment]
That’s good news!  Thank you.  @EveSnyder I think we can delete (or archive?) my “You Can’t Do That Merge” document and remove the link to it in my “Persons Enumerated Twice” document.

**Comment by PatientRowan** [comment]
I thought you had banished this condition?
![IMG_0396](https://github.com/historyforge/historyforge/assets/114665933/21cbc2a5-1c4c-444c-85a9-d6dda6972566)

**Comment by dfurber** [comment]
I just removed that check.
