### ISSUE TITLE
1850-1870 census data entry pages

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#220]
These censuses are somewhat simpler but also pose a few challenges and I wanted your opinion. 
1-address, the 1880 census was the first to include fields for the address. In this case I think we still want the same address fields so we can add that information and map them but I wanted to check. 
Along those same lines, the 1860 and 1870 censuses include a field for post office. As this can be different from the name of the town/city it can be helpful in finding people on a map and therefore I was thinking we should use it.

2-1850 census-no field for page number. I think we should include a field for the page anyway. In some cases like Ithaca they wrote it anyway, other towns didn't. If there isn't a page number the help text can instruct people to use the Familysearch image number.

3-Race on the 1860 and 1870 census-the instructions were to leave race blank for white. I think the best way to handle this is rather than W-White since that wasn't the case, to use the Blank [Blank/Blank Field/Blank Space?]-
Blank-White 
B-Black
M-Mulatto

4-Deaf and Dumb, Blind, Insane, Idiotic, Pauper, or Convict on the 1850-1860 census
The enumerator instructions state that in the case of an institution the census taker should indicate the dwelling number and  "must write after the number, and  perpendicularly in the same column (No. 1) the nature of such institution—that it is a penitentiary, jail, house of refuge, as the case may be; and in column 13, opposite the name of each person, he must state the character of the infirmity or misfortune, in the one case, and in the other he must state the crime for which each inmate is convicted, and of which such person was convicted; and in column No. 3, with the name, give the year of conviction" 
It seems we should have a separate field for institution type to capture that and I'm not sure where the rest of this information should go-in this field following convict?

**Comment by EveSnyder** [comment]
[1850-1870 census.xlsx](https://github.com/historyforge/historyforge/files/11548404/1850-1870.census.xlsx)

**Comment by PatientRowan** [comment]
I started working on the 1860 census manual, and wanted to mention that it may seem like overkill, but I think that County, Place, Locality, and Post Office are all different and valid elements to capture.

**Comment by dfurber** [comment]
I got these pretty much ready, and will deploy them when I'm satisfied it's all in order. But to answer your questions above, here's what I've done:

1. Yes keep the address or what are we doing here? :) I also added post office field for 1860 and 1870.
2. Your solution is good. Leave the field but have a better explanation.
3. I'm inclined to leave it as W and explain in help text. But I'll keep thinking about it. Mainly interested in consistency across years as much as possible.
4. For the institutional stuff on 1850 and 1860, I've added each of the things as an individual checkbox, otherwise they won't be searchable. I've also added an "Institution" section with name, type, reason for being there, and year. That should fit the needs for this data in a searchable way.

**Comment by PatientRowan** [comment]
It will be great to have them; I've written the manuals and ancillary documentation for each of the censuses, all on a speculative, hypothetical basis.  It was also easier to write the manuals one by one, as they get muddled up when you're working on 3 at the same time. Asking pardon in advance for the number of tweaks we will undoubtedly have when we start working with your forms and realize what we messed up.

For address, my provisional text in the manual is:
"Address fields were not included on the census until 1880. In some localities, however, it may be possible to determine a street address from reference sources or by other means. The address fields for this census have been included so that installations which are able to determine addresses for the individuals in the census during or after the initial transcription can enter them here to make it possible to map these records.
Consult your HistoryForge project coordinator for additional instructions."

**Comment by PatientRowan** [comment]
The language that @EveSnyder quoted for you about institution type applies only to the 1860 census, as far as I know.  I can't find anything about noting institutions in the 1850 census instructions. I could be wrong.

**Comment by PatientRowan** [comment]
I'm not sure what you mean about checkboxes for the "institutional stuff"?  Like, a checkbox for YES there was an institution type, AND a textual box to note the name of the institution?  They look like this, on the other side of the census sheet from Column 14:
![unnamed](https://github.com/historyforge/historyforge/assets/114665933/f1f9dac4-0e69-4a85-af92-eec2af111a9a)

**Comment by PatientRowan** [comment]
If you meant to use checkboxes for Deaf and Dumb, Blind, etc., without textual fields? the instructions have enumerators giving more than single word answers: "If a person be blind through a known cause, it would be well to insert the cause in the column or on the margin."  I found a teenage girl in Ithaca who is noted as "Insane, afraid of cats."

**Comment by dfurber** [comment]
Then I should combine the checkboxes with the reason + year, with institution name and type both being optional.

**Comment by dfurber** [comment]
And I just pushed the 1850, 1860, and 1870 stuff to Tompkins HF only, and enabled them for "private" but not "public" use. Please take a look and start the rounds of feedback.

To note:
Race for white folks on the relevant years now says "Blank - White" and doesn't have the "Left Blank" choice.
I reformatted the "institutions and why people would be in them" sections.

**Comment by PatientRowan** [comment]
I notice right away that the forms have fields for Enumeration Districts, but 1850, 1860 and 1870 didn’t use EDs. They just have Localities.
It’s going to take me a while but I will meet Eve later this afternoon, and then start making careful notes.

**Comment by dfurber** [comment]
I removed ED for these years.

**Comment by dfurber** [comment]
Closing because there are subsequent issue tickets with edits.
