### ISSUE TITLE
Missing Persons in Public Version of Person Records

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#307]
Compare this index in the non-public side:
![IMG_0574](https://github.com/historyforge/historyforge/assets/114665933/62d7ca71-a1c8-481d-a89a-a34dff4d19fc)

With this image from the public side:
![IMG_0576](https://github.com/historyforge/historyforge/assets/114665933/6f7164d7-4fc3-4628-8365-b5d85a068f74)

**Comment by PatientRowan** [comment]
I haven’t had time yet to figure out what is missing.  Is 1950 not included, for example?  I have a bad feeling about Louis Dean on that list, too.  Just making a start here.  I do not routinely look at the public side but this is not the first time I’ve noticed the problem.

**Comment by dfurber** [comment]
They are two different queries. "Last names starts with" knows that it's a last name and does an exact match on the start of the last names. The home page breaks up whatever you entered, runs each one through alternate/nickname matcher, and does a trigram search on each of them separated by "OR". That's why "Louis Dean" appears on the home page search, but not on the people page.

**Comment by dfurber** [comment]
And I suspect "Louis Dean" climbed the charts because there is trigram similarity between "Louis Dean" and "Deangelis".

**Comment by PatientRowan** [comment]
Different queries, but still, these three are kind-of not coming up in the public search on DeAngelis:
DeAngelis, Carole A
DeAngelis, Gloria J
DeAngelis, Hazel M
These 3 girls have a presence only in the 1950 census.
You can get to them by going further and starting to add the first names in the public search, so the search isn’t excluding them based on census appearance.  
I thought maybe the public search results list had a limit of some sort on the # of hits it would display, but I have seen some long search result lists so I don’t think that’s it?

**Comment by dfurber** [comment]
I think man should not put his faith in trigrams alone, but an alternative would require more attention. I switched it to use a simpler string comparison that would match "deangelis" but not "dean" without "gelis" when you search for "deangelis", but is less forgiving of sloppy typing.

**Comment by PatientRowan** [comment]
I tried my go-to name, the man who built my house, Ebenezer Miller.  It’s a weird search in the public view.  As I type the four letters Eben, I don’t get a single Ebenezer.  When I add another letter Ebene, I get a whole lot of Ebenezers, including mine.  But when I complete his name to Ebenezer, I’m back to the Eben results, without any Ebenezers.

**Comment by PatientRowan** [comment]
This lady, Imogene Stoner Hyde, died a week a go and her obituary just ran in the Journal: [https://www.ithacajournal.com/obituaries/pnys0730290](url)
I couldn’t find her under her birth name Stoner in HistoryForge.  Who knows what’s up with that.  But she does appear under the name of her first husband Costello: [https://tompkins.historyforge.net/people/191303](url)
I can’t make her come up in the search off the home page.  I tried last name first, first name first, and tried to type slowly to give the computer a chance to think about what to supply.  But she’s just not there, as far as I can see.  Her person record was created in Feb. 2023, so it’s not a time lag problem.

**Comment by dfurber** [comment]
Playing with Ebenezer Miller, I realize that there was an improvement to make to the way I was breaking the name down to search. Basically, if you enter "eb" we know that the first or last name starts with "eb". I was having it search for "eb" within the name. Thus "Webb" comes up when you know we aren't searching for anyone named "Webb".

What I ended up doing was taking what you type, running it through the cognates (which it was already doing). If it's a cognate, then it will look for an exact match on the first name for one of the cognates. Otherwise, it will look for whether the first or last name starts with the name. The reason is you could type "miller eben".

Also "Imogene Costello" comes right up. I think to get Hyde or Stoner, you need to add name variants, if you haven't already.

**Comment by PatientRowan** [comment]
Thank you.  It's definitely a whole lot better.
