### ISSUE TITLE
Can't open certain building records when not logged in

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge#352]
I was alerted to this by someone else and I am having the same problem trying to get to 143 E State St and certain other buildings (generally E State St) when not logged in. I can access them when logged in but when not logged in and I try to access it from any access point I can think of-main page, buildings database, The Forge (from nearby buildings, it sends me back to the main page with a red message "sorry you do not have permission to do that."
On The Forge a blank box pops up that doesn't even identify the street address
<img width="723" alt="Untitled1" src="https://github.com/historyforge/historyforge/assets/57808782/1cc548bd-5933-4861-8347-25c05c561f19">
But other nearby addresses show up with the address like normal.

**Comment by dfurber** [comment]
Yes, when I was working on narratives, I realized that any logged in person could view a lot of things that aren't reviewed yet. That was fine when the public couldn't sign up for HF account and upload stuff. So I made it more fine-grained as to which roles can view unreviewed stuff.

I keyed off of the `reviewed_by_id` key instead of `reviewed_at`. I think this exposed that if for some reason the `reviewed_by_id` is null, then it would deny permission to view the building.

You can see it because you can always see everything.

**Comment by dfurber** [comment]
Please reopen or create a new issue if my fix didn't resolve it.
