### ISSUE TITLE
Match on Race Problems

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#382]
I have a bad feeling about the person record algorithm matching on race.  I ran into a problem on the first day I was test-driving it: somebody whose family members were all getting matches, why no match for her?  It was because the transcriber had missed the Race radio button and left it blank.  This is a trivial error but I have an example of a more serious situation that is not as uncommon as one might think. @EveSnyder please let us know what you think.
A person whose race was recorded differently over time:
![IMG_0742](https://github.com/user-attachments/assets/689b8aaa-7015-494d-bb4e-97cff40bc09d)
His person record is set at Race=Mulatto.  I went into a census record in which he was recorded as White, and removed his Person ID.  As expected, no match was then offered on the right person:
![IMG_0743](https://github.com/user-attachments/assets/8d0a4c96-e537-4b3b-b8a9-510395500def)

**Comment by EveSnyder** [comment]
Matching on race sounds good in theory but because of the way the census identified race (visual identification)  it's problematic. We have people whose race is listed as Mexican on the 1930 census but white on all others because it was only a race on the census in 1930, we also have people whose race is Filipino on one census but white on all others because there were no instructions around identifying that race (not pob or anything else) so it was really up to the individual enumerator. In other words, it would be like matching on sex in a current census in Ithaca if sex was defined through visual identification by multiple enumerators. Each enumerator would have their own ideas and opinions regarding the concept of sex that would inform their designation so a person's sex on the census could easily vary from census to census.

**Comment by dfurber** [comment]
I removed race from the person matching.

**Comment by PatientRowan** [comment]
Thank you, Dave.  I'm glad I don't have to rewrite the manual.
