### ISSUE TITLE
Uncensused person matching outside age limits

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#403]
The match was suggested to me this morning.  My person, A Howard Genung, is 39 years old and matches to Aron, the first suggestion.  I've never seen a match suggested so far out of age boundaries in the second guy, Dr Homer Albert Genung, age 83:

![Screen Shot 2024-12-07 at 8 54 33 AM](https://github.com/user-attachments/assets/9e3c06cc-60cd-416f-baef-6c22b6a8bcd2)

But I don't think the program is broken.  @EveSnyder put this person record in yesterday, and he does not have any census appearances yet:

![Screen Shot 2024-12-07 at 8 59 31 AM](https://github.com/user-attachments/assets/e3cd07d5-6986-4d1b-a9a6-d2d39e5c4f88)

Any ideas?

**Comment by dfurber** [comment]
The person matching is set to ignore age if the person record has no census records. I'm changing it to not do that, but instead to ignore age only if the person record doesn't have a birth year. If it has a census record, it will have a birth year. Otherwise it will have a birth year only if you entered one.

I can also change it to ignore matches that don't have a birth year. LMK.

**Comment by PatientRowan** [comment]
That's a subtle and wise exception, which I will have forgotten if it ever happens to me--but thank you for your ability to think  around the corners ahead.
