### ISSUE TITLE
sign in with facebook

### ISSUE THREAD

**Issue by dfurber** [historyforge/historyforge#8]
Using OmniAuth or other standard Rails-based "log into Facebook" gem that interacts with Devise. Make it optional as a feature.

**Comment by jass2** [comment]
Hey!
Congratulations on your award in historic preservation!

Sorry for the absence, I was down a MacBook for a week while my partner's was being repaired. Here's the current progress on facebook authentication, all of the appropriate redirects are in order & the impl was pretty simple to throw together. I'm not entirely sure how production handles credentials, so I've commented out an extra line in the devise initializer. 

After adding in the button, I noticed the user page is now in slim format, I'll follow up this commit converting the login view the next chance I get.

Let me know what you think so far.

**Comment by dfurber** [comment]
Thanks! Yes you should definitely merge anytime you start a new feature/issue/thing.

Credentials can be handled in one of two ways:
1. Environment variables
2. Settings

The advantage of environment variables is that it is easy to spin up as a developer. The advantage of settings is that they can be manipulated through the settings UI.

Another thing to consider (and tweak in your code) is that not every HF instance will use FB logins. Probably most won't to start, since it involves multiple steps on FB that will scare small children. So it needs to be easy to turn the feature on and off. Also we will need instructions how to configure it.

And I should write some instructions on how the env vars and settings work...

**Comment by jass2** [comment]
Oh right! I forget that HF is deployed outside of just THC. 

So it sounds like Devise should use one or the other depending on the build environment, and that, in a production build, for it ought to connect to the APP_ID/secret passed through admin settings UI (as well as some switch toggling the facebook auth service in the first place). Is this the intention of the provider table? columns for appId, secret, name, enabled, etc... 

Also, something that came up, is that 'login' is a required attribute for the user table, but the value isn't necessarily set for a user creating an account through OAuth. Is the removal of the :required tag justified here?

If so, I could see some end-user admins manually creating accounts without a login, which seems bad. Should we instead set a pseudo-login based on some info found in the credential returned from the provider? Thoughts?

**Comment by dfurber** [comment]
Hi Jason,

Keep the login field. You could take the email address before the @ and add digits as needed to avoid conflicts.

Those oauth tables are detritus from MapWarper - I'd look there to see how they are used. If no longer helpful they can be axed, or left on the woodpile.

I wouldn't let Devise decide what app id and secrets to use. I would use the AppConfig system. You can start with ENV vars and I can take it from there if I don't AppConfig documented before you get to it.

**Comment by dfurber** [comment]
Hi @jass2 I added wiki pages about developer setup and app config. That should help you get some census data in your dev database, and tell you how to make settings for Facebook app id and secret, and its feature flag.

**Comment by jass2** [comment]
Great! I'll look into that tomorrow. I've certainly been dragging my feet on entering test data

**Comment by jass2** [comment]
I think I was able to figure out the correct env variable workflow here. Just have to add wiki instructions & pseudo-usernames for new facebook users and it should be set.

**Comment by jass2** [comment]
Wanted to give an update since it's been a while. The last couple of days I've been running in circles attempting to re-write to the .env file after the database goes online. It took a while to diagnose that being the problem, but I'm confident I'm on the right track. I'm currently configuring dokku locally to writeback to .env so on a new launch, an updated api key is present. 

One question I do have is that in the Devise initializer line 15 writes:

config.mailer_sender = proc { AppConfig.mail_from } 

I thought I could repeat this implementation for the facebook auth config, as written in the branch currently. However on execution and attempted auth re-direct, the AppId and Secret are <Proc> objects instead of their evaluated counterparts. Is there a particular reason we can reference AppConfig through a proc in this initializer for mailer_sender (assuming this is used and works as intended), but not for any auth config?

**Comment by dfurber** [comment]
Hello! I'm not sure what you mean about re-writing to the .env file after the database goes online, or why you're doing anything with Dokku in development. The .env file is simply a means to set environment variables in development, and has nothing to do with Dokku, where the same variables are set with `dokku config:set`.

To answer your question, I'm not convinced the mailer_sender proc works as intended, nor do I know whether the omniauth config has the same option to send a proc instead of a value. In any case it should be fine to use environment variables and reference them using AppConfig. The convention is ENV['APP_SECRET'] can be accessed as AppConfig.app_secret. Then later on I can set it dynamically as needed.

**Comment by jass2** [comment]
From my understanding, when the devise.rb initializer runs, it reads from the .env file via ENV['FACEBOOK_APP_ID'], since the Settings table & Appconfig.facebook_api_key is not yet online. 

that omniauth config value is then never updated to its associated Settings table value. I'm looking for the appropriate place to update the devise config key once the database goes online, which is when I believe I can access the updated value in AppConfig.facebook_api_key.

**Comment by jass2** [comment]
This branch works as initially intended. A few extra parts came up that likely need to be addressed before a merge.

1. Login is currently derived from Facebook-authed accounts as 'f_(facebook email)' . A better convention is probably necessary to avoid conflicts & maintain privacy. I'm curious if you had a better suggestion.

2. Facebook OmniAuth requires an SSL for any request or redirect URLs. I had to declare the cert and key locations in-line when launching the server and I'd be curious about how to integrate this information with any production instance.

3. As far as CRUD & data persistence, the Facebook App ID & Secret can be updated in the settings page similar to the Google API keys, however, in my own instance, the application insists on reading the data from the .env file regardless of those updated server entries in the Settings table (both google API keys and facebook keys). Everything reads fine from the .env otherwise. That's been a bit of a blocker locally, so if these values update fine for you after updating admin UI, I think it's good to go.
